name: 🏛️ Web Archive

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: 🌍 Get the current domain
        run: cat "CNAME" >> $GITHUB_ENV

      - name: 💾 Archive page
        id: archive
        uses: JamieMagee/wayback@a01961cced233578e9d5759a5acf4e573167e3a9 # v2.0.0
        with:
          url: ${{ env.CNAME }}
          saveScreenshot: true

      - run: echo "### ✅ Page successfully archived at ${{ steps.archive.outputs.wayback_url }}" >> $GITHUB_STEP_SUMMARY
